In [ ]:
import pandas as pd
import numpy as np
import config
import utils

In [2]:
# Load data
df_com = pd.read_csv("../data/data_communities.csv", index_col=[0])
df = pd.read_csv(config.FEATS_PATH, header=None)
#df_labels = pd.read_csv(config.LABELS_PATH)
df = df.merge(df_com, left_on=0, right_on="txId").drop(["txId"], axis=1)
df.loc[:, "target"] = df[1]

/tmp/ipykernel_2981/1452218435.py:6: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.loc[:, "target"] = df[1]

In [3]:
feats_auc = pd.DataFrame(columns=["feature", "auc"])
for feat in range(1, 167):
    auc = utils.pred_power(feat, "label", df.loc[~df.loc[:, "label"].isnull()])
    feats_auc.loc[len(feats_auc)] = [feat, auc]

In [ ]:
#feats_auc
#df.loc[~df.loc[:, "label"].isnull(), 1:166].corr()

,1,2,3,4,5,6,7,8,9,10,...,157,158,159,160,161,162,163,164,165,166
1,1.000000,0.055813,0.190364,0.582587,0.009908,-0.008799,0.014852,-0.020715,0.059765,0.055715,...,0.046966,0.049223,0.011196,0.010963,-0.007728,0.018951,0.046163,0.066069,-0.053668,-0.052865
2,0.055813,1.000000,0.070409,0.095649,0.043574,0.057970,0.036751,0.068972,0.831754,0.973266,...,0.032986,-0.009613,-0.014509,-0.016693,0.001084,0.198155,0.174772,0.112626,0.020071,0.019160
3,0.190364,0.070409,1.000000,0.256756,0.619014,0.031320,0.635275,0.169349,0.003108,0.032653,...,0.050961,0.024304,0.027570,0.028441,0.065861,0.043503,0.029552,0.058403,-0.002976,-0.003413
4,0.582587,0.095649,0.256756,1.000000,0.149501,0.011641,0.155193,0.021668,0.088281,0.088665,...,0.095576,0.122084,0.076001,0.075063,-0.003702,0.039374,0.046675,0.066978,-0.050922,-0.052909
5,0.009908,0.043574,0.619014,0.149501,1.000000,0.006044,0.985769,0.322540,-0.026573,0.000574,...,0.016093,0.000620,0.026704,0.027415,0.064482,0.027402,0.025243,0.050417,-0.008465,-0.009121
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,0.018951,0.198155,0.043503,0.039374,0.027402,0.112189,0.016904,0.130516,0.044613,0.162680,...,0.034096,0.022070,0.009193,0.011066,0.040710,1.000000,0.906896,0.669950,-0.015563,-0.009712
163,0.046163,0.174772,0.029552,0.046675,0.025243,0.017777,0.015968,0.116867,0.033124,0.141445,...,0.026100,0.016674,0.010674,0.012421,-0.004410,0.906896,1.000000,0.852395,-0.022330,-0.015918
164,0.066069,0.112626,0.058403,0.066978,0.050417,0.000337,0.042594,0.114036,0.018258,0.087274,...,0.001360,-0.003851,0.014452,0.015650,0.350956,0.669950,0.852395,1.000000,-0.033460,-0.028370
165,-0.053668,0.020071,-0.002976,-0.050922,-0.008465,-0.001668,-0.007893,-0.006925,0.023211,0.022139,...,0.075182,0.045835,-0.137896,-0.137520,-0.018017,-0.015563,-0.022330,-0.033460,1.000000,0.995125
166,-0.052865,0.019160,-0.003413,-0.052909,-0.009121,-0.002646,-0.008633,-0.006688,0.021566,0.021032,...,0.074862,0.045654,-0.140346,-0.139896,-0.017655,-0.009712,-0.015918,-0.028370,0.995125,1.000000

In [4]:
features_to_keep = utils.filter_corr(df.loc[~df.loc[:, "label"].isnull(), :], feats_auc)

KeyError: '[164.0, 162.0, 161.0, 160.0, 159.0, 158.0, 157.0, 156.0, 155.0, 154.0, 153.0, 152.0, 151.0, 147.0, 144.0, 142.0, 138.0, 137.0, 135.0, 129.0, 128.0, 127.0, 126.0, 125.0, 124.0, 123.0, 122.0, 121.0, 120.0, 119.0, 118.0, 117.0, 116.0, 115.0, 114.0, 113.0, 111.0, 107.0, 104.0, 103.0, 101.0, 98.0, 97.0, 95.0, 94.0, 93.0, 92.0, 91.0, 89.0, 88.0, 87.0, 85.0, 84.0, 82.0, 81.0, 78.0, 77.0, 76.0, 75.0, 74.0, 73.0, 72.0, 71.0, 70.0, 69.0, 68.0, 64.0, 62.0, 60.0, 58.0, 57.0, 56.0, 55.0, 51.0, 50.0, 49.0, 48.0, 47.0, 46.0, 45.0, 43.0, 42.0, 41.0, 40.0, 39.0, 38.0, 37.0, 36.0, 35.0, 34.0, 33.0, 32.0, 28.0, 26.0, 24.0, 23.0, 22.0, 21.0, 20.0, 19.0, 18.0, 15.0, 14.0, 13.0, 12.0, 8.0, 7.0, 6.0, 5.0, 4.0, 2.0, 1.0] not in index'

In [5]:
feats_auc.loc[:, "feature"].tolist()

[1.0,
 2.0,
 3.0,
 4.0,
 5.0,
 6.0,
 7.0,
 8.0,
 9.0,
 10.0,
 11.0,
 12.0,
 13.0,
 14.0,
 15.0,
 16.0,
 17.0,
 18.0,
 19.0,
 20.0,
 21.0,
 22.0,
 23.0,
 24.0,
 25.0,
 26.0,
 27.0,
 28.0,
 29.0,
 30.0,
 31.0,
 32.0,
 33.0,
 34.0,
 35.0,
 36.0,
 37.0,
 38.0,
 39.0,
 40.0,
 41.0,
 42.0,
 43.0,
 44.0,
 45.0,
 46.0,
 47.0,
 48.0,
 49.0,
 50.0,
 51.0,
 52.0,
 53.0,
 54.0,
 55.0,
 56.0,
 57.0,
 58.0,
 59.0,
 60.0,
 61.0,
 62.0,
 63.0,
 64.0,
 65.0,
 66.0,
 67.0,
 68.0,
 69.0,
 70.0,
 71.0,
 72.0,
 73.0,
 74.0,
 75.0,
 76.0,
 77.0,
 78.0,
 79.0,
 80.0,
 81.0,
 82.0,
 83.0,
 84.0,
 85.0,
 86.0,
 87.0,
 88.0,
 89.0,
 90.0,
 91.0,
 92.0,
 93.0,
 94.0,
 95.0,
 96.0,
 97.0,
 98.0,
 99.0,
 100.0,
 101.0,
 102.0,
 103.0,
 104.0,
 105.0,
 106.0,
 107.0,
 108.0,
 109.0,
 110.0,
 111.0,
 112.0,
 113.0,
 114.0,
 115.0,
 116.0,
 117.0,
 118.0,
 119.0,
 120.0,
 121.0,
 122.0,
 123.0,
 124.0,
 125.0,
 126.0,
 127.0,
 128.0,
 129.0,
 130.0,
 131.0,
 132.0,
 133.0,
 134.0,
 135.0,
 136.0,
 137.0,
 138.0,
 139.0,
 140.0,
 141.0,
 142.0,
 143.0,
 144.0,
 145.0,
 146.0,
 147.0,
 148.0,
 149.0,
 150.0,
 151.0,
 152.0,
 153.0,
 154.0,
 155.0,
 156.0,
 157.0,
 158.0,
 159.0,
 160.0,
 161.0,
 162.0,
 163.0,
 164.0,
 165.0,
 166.0]

In [7]:
feats_auc

     feature       auc
0        1.0  0.496079
1        2.0  0.374358
2        3.0  0.443686
3        4.0  0.475640
4        5.0  0.307045
..       ...       ...
161    162.0  0.255064
162    163.0  0.314127
163    164.0  0.286001
164    165.0  0.463135
165    166.0  0.463711

[166 rows x 2 columns]